In [3]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
df = pd.read_csv("cars.csv", delimiter=';')
cols= ['Sports Car?', 'Wagon?', 'Minivan?', 'Pickup?', 'All-Wheel Drive?', 'Rear-Wheel Drive?', 'Suggested Retail Price', 'Dealer Cost', 'Engine Size', 'Number of Cylinders', 'Horsepower', 'City Miles Per Gallon', 'Highway Miles Per Gallon', 'Weight', 'Wheel Base', 'Length', 'Width']
data = df[cols]
data.head()

Sports Car?  Wagon?  Minivan?  Pickup?  All-Wheel Drive?  \
0            0       0         0        0                 0   
1            0       0         0        0                 0   
2            0       0         0        0                 0   
3            0       0         0        0                 0   
4            0       0         0        0                 0   

   Rear-Wheel Drive?  Suggested Retail Price  Dealer Cost  Engine Size  \
0                  0                   11690        10965          1.6   
1                  0                   12585        11802          1.6   
2                  0                   14610        13697          2.2   
3                  0                   14810        13884          2.2   
4                  0                   16385        15357          2.2   

   Number of Cylinders  Horsepower  City Miles Per Gallon  \
0                    4         103                     28   
1                    4         103                     28   
2                    4         140                     26   
3                    4         140                     26   
4                    4         140                     26   

   Highway Miles Per Gallon  Weight  Wheel Base  Length  Width  
0                        34    2370          98     167     66  
1                        34    2348          98     153     66  
2                        37    2617         104     183     69  
3                        37    2676         104     183     68  
4                        37    2617         104     183     69

In [112]:
X_train, X_test, Y_train, Y_test = train_test_split(data.values, df['Sport Utility Vehicle?'].values, random_state=0)
X_test

array([[  0.,   0.,   0., ..., 108., 191.,  71.],
       [  0.,   0.,   0., ..., 108., 191.,  72.],
       [  0.,   0.,   0., ..., 109., 190.,  74.],
       ...,
       [  0.,   1.,   0., ...,  99., 175.,  68.],
       [  0.,   0.,   0., ...,  99., 168.,  68.],
       [  0.,   0.,   0., ..., 115., 194.,  73.]])

In [90]:
knn = KNeighborsClassifier(n_neighbors = 2) # k = 1,2,3
knn.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=2)

In [91]:
x_new1 = np.array([[0, 0, 0, 0, 1, 0, 41475, 36494, 6, 10, 310, 15, 19, 7190, 137, 227, 80]]) #внедорожник
x_new2 = np.array([[1, 0, 0, 0, 0, 1, 33500, 30710, 5, 8, 340, 19, 26, 3725, 110, 190, 73]]) # не внедорожник
prediction1 = knn.predict(x_new1)
prediction2 = knn.predict(x_new2)
prediction1, prediction2

(array([0], dtype=int64), array([0], dtype=int64))

In [92]:
knn.score(X_test, Y_test)

0.8762886597938144

In [93]:
import scipy as sp

In [102]:
contingency_table = sp.sparse.coo_matrix((np.ones_like(Y_test), (X_test[:, 0], Y_test)), shape=(np.unique(X_test[:, 0]).shape[0], np.unique(Y_test).shape[0])).A
contingency_table

array([[64, 16],
       [17,  0]], dtype=int64)